# Generated by Django 5.1.6 on 2025-02-13 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('league_id', models.IntegerField(default=475)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('odds_team1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_team2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_team1', models.IntegerField(blank=True, default=0, null=True)),
                ('score_team2', models.IntegerField(blank=True, default=0, null=True)),
                ('match_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='upcoming', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('match_winner', 'Match Winner')], default='match_winner', max_length=50)),
                ('bet_choice', models.CharField(max_length=50)),
                ('amount_user_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_user_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selected_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_created', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_received', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_bets', to=settings.AUTH_USER_MODEL)),
                ('bet_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckyshot_main_app.match')),
            ],
        ),
    ]
