# Generated by Django 5.1.6 on 2025-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyshot_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
